music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.index, name='index'),

    # /music/71/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    # /music/71/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite')
]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^music/', include('music.urls')),
    url(r'^admin/', admin.site.urls),
]

music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Songs(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Songs
import pprint

def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums': all_albums})


def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.songs_set.get(pk=request.POST['song'])
    except (KeyError, Songs.DoesNotExists):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': "You did not select a valid song"
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

music/templates/music/detail.html
<strong>{{ album.artist }}</strong>: {{ album.album_title }}

<ul>
    {% for song in album.songs_set.all %}
        <li>{{ song.song_title }}</li>
    {% endfor %}
</ul>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.songs_set.all %}
    <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
    <label for="song{{ forloop.counter }}">
        {{ song.song_title }}
        {% if song.is_favorite %}
            Favorite!
        {% endif %}
    </label> <br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

music/templates/music/index.html
{% if all_albums %}
<h3>Here are all my albums:</h3>
<ul>
    {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title}}</a></li>
    {% endfor %}
</ul>
{% else %}

    <h3>You don't have any albums.</h3>

{% endif %}